<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<!-- EF Core Design is needed for migrations -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<!-- EF Core SQL Server provider -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />

		<!-- EF Core Tools for CLI commands -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TrackNest.Application\TrackNest.Application.csproj" />
		<ProjectReference Include="..\TrackNest.Domain\TrackNest.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Configurations\" />
	</ItemGroup>

</Project>
